version: 2

sources:
  - name: raw
    database: groovy-gearbox-402208
    schema: gz_raw_data
    tables:
      - name: raw_gz_sales
        identifier: sales
      - name: raw_gz_product
        identifier: product
      - name: raw_gz_ship
        identifier: ship
