version: 2

sources:
  - name: raw
    database: groovy-gearbox-402208
    schema: gz_raw_data
    descripton: greenweez raw data source 
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez/ we have a row per product_id found in each order_id
        columns:
          - name: date_date
            description: the date of purchase
      - name: product
        identifier: raw_gz_product
        description: purchase price for each product id
      - name: ship
        identifier: raw_gz_ship
        description: shipping cost for each order
