version: 2

sources:
  - name: raw
    database: groovy-gearbox-402208
    schema: gz_raw_data
    description: greenweez raw data source 
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez/ we have a row per product_id found in each order_id
        freshness: 
          warn_after: 
            count: 90
            period: day
        loaded_at_field: "CAST (date_date as timestamp)"
        
        columns:
          - name: date_date
            description: the date of purchase
          - name: "(pdt_id || '-' || orders_id)"
            tests: 
              - unique
              - not_null
              
        
      - name: product
        identifier: raw_gz_product
        description: purchase price for each product id
        columns:
          - name: products_id
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: shipping cost for each order
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
      
      - name: adwords
        identifier: raw_gz_adwords
        description: information about the campaign with adwords as data source

      - name: bing
        identifier: raw_gz_bing
        description: information about the campaign with bing as data source

      - name: criteo
        identifier: raw_gz_criteo
        description: information about the campaign with criteo as data source

      - name: facebook
        identifier: raw_gz_facebook
        description: information about the campaign with facebook as data source
 